### ISSUE TITLE
not working with 10.0.0

### ISSUE THREAD

**Issue by MoSardy** [mrmans0n/smart-location-lib#180]
**dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile project(':BaseGameUtils')

    compile 'com.google.android.gms:play-services-games:10.0.0'
    compile 'com.google.android.gms:play-services-maps:10.0.0'
    compile 'com.google.firebase:firebase-database:10.0.0'
    compile 'com.android.support:appcompat-v7:25.0.1'
    compile 'com.android.support:design:25.0.1'
    compile 'com.msg91.sendotp.library:library:2.7'
    compile 'swarajsaaj:otpreader:1.0'
    compile 'com.github.florent37:viewanimator:1.0.4'
    compile 'rb.popview:popview:0.1.0'
    testCompile 'junit:junit:4.12'
    compile ('io.nlopez.smartlocation:library:3.2.9') {
        transitive = false
    }**

error:

 java.lang.NoClassDefFoundError: io.nlopez.smartlocation.location.providers.LocationGooglePlayServicesProvider
                                                       at io.nlopez.smartlocation.location.providers.LocationGooglePlayServicesWithFallbackProvider.<init>(LocationGooglePlayServicesWithFallbackProvider.java:32)
                                                       at io.nlopez.smartlocation.SmartLocation.location(SmartLocation.java:59)
                                                       at in.dsardy.pingerme.MapsActivity.onMapReady(MapsActivity.java:44)
                                                       at com.google.android.gms.maps.SupportMapFragment$zza$1.zza(Unknown Source)
                                                       at com.google.android.gms.maps.internal.zzt$zza.onTransact(Unknown Source)
                                                       at android.os.Binder.transact(Binder.java:310)
                                                       at aai.a(:com.google.android.gms.DynamiteModulesB:82)
                                                       at maps.ad.t$5.run(Unknown Source)
                                                       at android.os.Handler.handleCallback(Handler.java:725)
                                                       at android.os.Handler.dispatchMessage(Handler.java:92)
                                                       at android.os.Looper.loop(Looper.java:176)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5302)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:511)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
                                                       at dalvik.system.NativeStart.main(Native Method)

**Comment by fangzhzh** [comment]
same here
